  main = ".open-next/worker.js"
  name = "windly"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"
[env.production.vars]
NEXTAUTH_URL    = "https://windly.dababy.workers.dev"
AUTH_TRUST_HOST = "https://windly.dababy.workers.dev"
